import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    environment: "node",
    coverage: {
      provider: "v8",
      reporter: ["lcov", "html", "text"],
      include: [
        "src/contacts/contactConnections.ts",
        "src/events/eventPolicy.ts",
        "src/events/eventList.ts",
        "src/community/communityApi.ts",
        "src/community/communityFeedback.ts",
        "src/organizations/organizationActions.ts",
        "src/events/eventForm.ts",
        "src/events/eventWizardForm.ts",
        "src/matches/matchParticipants.ts",
        "src/organizations/organizationLogoUpload.ts",
        "src/contacts/hooks/contactOptimistic.ts",
        "src/matches/matchCard.ts",
        "src/locations/locationAddress.ts",
        "src/matches/matchContactState.ts",
        "src/matches/matchResults.ts",
        "src/contacts/phoneCountries.ts",
      ],
      thresholds: {
        "src/events/eventList.ts": { lines: 100, functions: 100, branches: 100, statements: 100 },
        lines: 50,
        functions: 50,
        branches: 50,
        statements: 50,
        "src/community/communityApi.ts": {
          lines: 100,
          functions: 100,
          branches: 100,
          statements: 100,
        },
        "src/community/communityFeedback.ts": {
          lines: 100,
          functions: 100,
          branches: 100,
          statements: 100,
        },
        "src/events/eventWizardForm.ts": {
          lines: 100,
          functions: 100,
          branches: 100,
          statements: 100,
        },
        "src/events/eventForm.ts": {
          lines: 100,
          functions: 100,
          branches: 100,
          statements: 100,
        },
        "src/matches/matchParticipants.ts": {
          lines: 100,
          functions: 100,
          branches: 100,
          statements: 100,
        },
        "src/organizations/organizationActions.ts": {
          lines: 100,
          functions: 100,
          branches: 100,
          statements: 100,
        },
        "src/organizations/organizationLogoUpload.ts": {
          lines: 100,
          functions: 100,
          branches: 100,
          statements: 100,
        },
        "src/events/eventPolicy.ts": {
          lines: 100,
          functions: 100,
          branches: 100,
          statements: 100,
        },
        "src/contacts/contactConnections.ts": {
          lines: 100,
          functions: 100,
          branches: 100,
          statements: 100,
        },
        "src/contacts/hooks/contactOptimistic.ts": {
          lines: 100,
          functions: 100,
          branches: 100,
          statements: 100,
        },
        "src/matches/matchCard.ts": {
          lines: 100,
          functions: 100,
          branches: 100,
          statements: 100,
        },
        "src/matches/matchContactState.ts": {
          lines: 100,
          functions: 100,
          branches: 100,
          statements: 100,
        },
        "src/matches/matchResults.ts": {
          lines: 100,
          functions: 100,
          branches: 100,
          statements: 100,
        },
        "src/locations/locationAddress.ts": {
          lines: 100,
          functions: 100,
          branches: 100,
          statements: 100,
        },
        "src/contacts/phoneCountries.ts": {
          lines: 100,
          functions: 100,
          branches: 100,
          statements: 100,
        },
      },
    },
  },
});
